[package]
name = "meml-transcriber"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
byteorder = "1.5.0"
candle-core = { version = "0.9.2", features = ["metal", "accelerate"] }
candle-nn = { version = "0.9.2", features = ["metal"] }
candle-transformers = "0.9.2"
clap = { version = "4.5.60", features = ["derive"] }
hf-hub = "0.4.0"
hound = "3.5.1"
rand = "0.10.0"
rodio = "0.21.1"
rubato = "0.14.0"
serde_json = "1.0.149"
symphonia = { version = "0.5.5", features = ["all"] }
tokenizers = "0.22.2"
